export const MODIFY_CLIENT_SELECTED_REQUEST = "@client/main_view/MODIFY_SELECTED_REQUEST";
export const MODIFY_CLIENT_SELECTED_PROPOSAL = "@client/main_view/MODIFY_SELECTEd_PROPOSAL";
export const CLOSE_CLIENT_REQUEST_CREATION_POPUP = "@client/main_view/CLOSE_REQUEST_CREATION_WINDOW";
export const CLOSE_CLIENT_PROPOSAL_DETAILS_POPUP = "@client/proposal_details_display/CLOSE_PROPOSAL_DETAILS_WINDOW";
